### ISSUE TITLE
Revision history is not working

### ISSUE THREAD

**Issue by btel** [codenode/codenode#44] opened 2010-07-08 13:11 UTC
When I click revision history the "'AuditTrailManager' object has no attribute '_db'" error is thrown.

**Comment by jamescasbon** [comment] 2010-07-11 19:13
Confirmed.  See also #38

**Comment by jamescasbon** [comment] 2010-07-11 19:26
Looks like this is broken: http://code.djangoproject.com/wiki/AuditTrail

**Comment by jamescasbon** [comment] 2010-07-11 19:30
From http://stackoverflow.com/questions/818823/django-audittrail-vs-reversion
"""
I assume by AuditTrail you mean AuditTrail on the Django wiki. If so, I think you'll want to instead look at HistoricalRecords  developed by the same author (Marty Alchin aka @gulopine) in his book Pro Django. It should work better with Django 1.x.
""" 

Doesn't look good for AuditTrail

**Comment by jamescasbon** [comment] 2010-07-11 19:49
updated AuditTrail. Closed by bf9abd15dfcab12d164560f25909a01f8c145494

**Closed as completed by jamescasbon** 2010-07-11 19:49 UTC
